//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylmData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class alcontent
    {
        public int id { get; set; }
        public string content { get; set; }
        public int baslikid { get; set; }
        public int status { get; set; }
    
        public virtual altbaslik altbaslik { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
