//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylmData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogYazi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogYazi()
        {
            this.Sliders = new HashSet<Slider>();
            this.yorumlars = new HashSet<yorumlar>();
        }
    
        public int id { get; set; }
        public string Baslik { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> aySira { get; set; }
        public string tanitimYazi { get; set; }
        public string folder { get; set; }
        public string path { get; set; }
        public string aylar { get; set; }
    
        public virtual picture picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slider> Sliders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorumlar> yorumlars { get; set; }
    }
}
