//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylmData.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oylmzEntities : DbContext
    {
        public oylmzEntities()
            : base("name=oylmzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alcontent> alcontents { get; set; }
        public virtual DbSet<altbaslik> altbasliks { get; set; }
        public virtual DbSet<BlogYazi> BlogYazis { get; set; }
        public virtual DbSet<calismagun> calismaguns { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<KoclukNedir> KoclukNedirs { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<sliYazi> sliYazis { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<yorumlar> yorumlars { get; set; }
        public virtual DbSet<yorumDanisan> yorumDanisans { get; set; }
        public virtual DbSet<sertifikalar> sertifikalars { get; set; }
    }
}
