//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylmData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int id { get; set; }
        public string folder { get; set; }
        public int bId { get; set; }
        public string path { get; set; }
    
        public virtual BlogYazi BlogYazi { get; set; }
    }
}
