//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylmData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int ID { get; set; }
        public string sliderContent { get; set; }
        public string buyuk { get; set; }
        public string orta { get; set; }
        public string kucuk { get; set; }
        public Nullable<int> byaziid { get; set; }
        public int status { get; set; }
        public string path { get; set; }
    
        public virtual BlogYazi BlogYazi { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
