//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylmData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sliYazi
    {
        public int id { get; set; }
        public string yazi1 { get; set; }
        public string yazi2 { get; set; }
        public string yazi3 { get; set; }
    }
}
