//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylmData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int tID { get; set; }
        public string tokentext { get; set; }
        public System.DateTime enddate { get; set; }
        public int userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
